[project]
name = "2025-spring-edge-ai-lab4"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "eager>=0.0.1",
    "optimum[onnxruntime]>=1.25.3",
    "qai-hub-models[lama-dilated]>=0.30.2",
]
